GP-822 Self-healing Loop
guardian/pluto-storagetier pull request #42
Opened 2022-12-21 10:57 UTC by danielhedlund

## What does this change?

## Why is the change needed?

## Important implementation details

## Risks to consider when deploying

2022-12-22 10:05 UTC, fredex42 requested changes
Few small changes but generally great work as always

2022-12-22 15:00 UTC, danielhedlund commented on media_remover/src/main/scala/OnlineArchiveMessageProcessor.scala
> +            throw SilentDropMessage(Some(s"No nearline ID in pending deletion rec for media ${archivedRecord.originalFilePath}"))
Ah yes, makes sense.

2022-12-28 15:10 UTC, danielhedlund commented on media_remover/src/main/scala/helpers/NearlineHelper.scala
> +      metaRes <- deleteSingleAttMedia(vault, objectMatrixEntry, "ATT_META_OID", nearlineId, originalFilePath)
https://github.com/guardian/pluto-storagetier/blob/4d77ab463c790a656690f6084b36968240f2b5ef/online_nearline/src/main/scala/matrixstore/CustomMXSMetadata.scala#L88 would highly suggest that they are.

2022-12-28 15:36 UTC, danielhedlund commented on media_remover/src/test/scala/helpers/NearlineHelperSpec.scala
> +          override protected def callObjectMatrixEntryFromOID(vault: Vault, fileName: String): Future[ObjectMatrixEntry] = Future.fromTry(Failure(new RuntimeException("no oid for you")))
Ahyes!

2023-01-02 12:25 UTC, danielhedlund commented on media_remover/src/main/scala/S3ObjectChecker.scala
> +  private def mediaExistsInDeepArchive(mediaTier: String, checksumMaybe: Option[String], fileSize: Long, originalFilePath: String, objectKey: String): Future[Boolean] =
Right!

2023-01-02 15:16 UTC, danielhedlund commented on media_remover/src/test/scala/S3ObjectCheckerSpec.scala
> +//
Yeah

2023-01-02 16:43 UTC, danielhedlund commented on media_remover/src/main/scala/helpers/NearlineHelper.scala
> +      //TODO add nearlineId to parameter list for logging purposes(?)
😅

2023-01-02 16:45 UTC, danielhedlund commented on media_remover/src/main/scala/helpers/NearlineHelper.scala
> +    // TODO do we need to wrap this with a Future.fromTry?
Alright

2023-01-02 16:50 UTC, danielhedlund commented on media_remover/src/main/scala/helpers/PendingDeletionHelper.scala
> +    (msg.mediaTier, msg.vidispineItemId, msg.nearlineId) match {
Yeah, should have been a different type in the `OnlineOutputMessage`

2023-01-02 16:59 UTC, danielhedlund commented on media_remover/src/main/scala/helpers/PendingDeletionHelper.scala
> +                pendingDeletionRecordDAO.findByOnlineIdForONLINE(Ensurer.validateNeededFields(Some(0), Some(""), msg.vidispineItemId)._3)
Changing to `Ensurer.validateMediaId`

2023-01-02 19:34 UTC, danielhedlund commented on media_remover/src/main/scala/helpers/NearlineHelper.scala
> +        // TODO Decide if we need to/should do this? Flip it around maybe?
Alright, makes sense

2023-01-02 21:11 UTC, danielhedlund commented on media_remover/src/main/scala/OnlineArchiveMessageProcessor.scala
> +    val (_, _, vsItemId) = Ensurer.validateNeededFields(Some(1), Some("path"), archivedRecord.vidispineItemId)
Will use `Ensurer.validateMediaId` instead

2023-01-05 15:45 UTC, danielhedlund commented on media_remover/src/main/scala/OnlineArchiveMessageProcessor.scala
> +      // byVsItemId <- pendingDeletionRecordDAO.findByOnlineIdForNEARLINE(archivedRecord.vidispineItemId // maybe?)
Reworked this to get all `PendingDeletionRecord`s by `originalFilePath`, and check all until one is found, using `Future.find()` etc.

2023-01-06 16:28 UTC, fredex42 requested changes
Apologies, couple more things to fix :(

2023-01-06 16:28 UTC, fredex42 commented on media_remover/src/test/scala/OnlineArchiveMessageProcessorSpec.scala
> +//        Future(Right(MediaRemovedMessage("NEARLINE", anOriginalFilePath, Some("VX-33"), Some("mxs-33")).asJson))
Can we zap the commented lines?

2023-01-06 16:28 UTC, fredex42 commented on media_remover/src/test/scala/OnlineArchiveMessageProcessorSpec.scala
> +//      mediaRemovedMessage.mediaTier mustEqual MediaTiers.NEARLINE.toString
:zap:

2023-01-10 13:28 UTC, danielhedlund commented on media_remover/src/main/scala/S3ObjectChecker.scala
> +        logger.warn(s"Could not connect to deep archive to check if copy of $mediaTier media exists, do not delete. Err: ${err.getMessage}")
Alrighty!

2023-01-10 14:49 UTC, danielhedlund commented on media_remover/src/main/scala/OnlineNearlineMessageProcessor.scala
> +                    pendingDeletionRecordDAO.updateAttemptCount(rec.id.get, rec.attempt + 1)
Added

2023-01-10 14:49 UTC, danielhedlund commented on media_remover/src/test/scala/OnlineArchiveMessageProcessorSpec.scala
> +//        Future(Right(MediaRemovedMessage("NEARLINE", anOriginalFilePath, Some("VX-33"), Some("mxs-33")).asJson))
Yup!

2023-01-10 14:49 UTC, danielhedlund commented on media_remover/src/test/scala/OnlineArchiveMessageProcessorSpec.scala
> +//      mediaRemovedMessage.mediaTier mustEqual MediaTiers.NEARLINE.toString
Begone!

2023-01-10 18:39 UTC, fredex42 approved these changes
And with that mammoth effort, we're done :partying_face: :tada:

2023-01-11 09:59 UTC, merged